amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: scan
    map_topic: map
    min_particle_weight: 0.0001
    kld_err: 0.05
    kld_z: 0.99
    update_min_a: 0.2
    update_min_d: 0.25
    resample_interval: 1
    max_particles: 2000
    min_particles: 500
    laser_model_type: likelihood_field
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    z_hit: 0.9
    z_rand: 0.1
    sigma_hit: 0.2
    tf_broadcast: true

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""   # set via launch arg

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      # WRONG:
      # plugin: "nav2_regulated_pure_pursuit_controller/NavfnPlanner"
      # plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"

      # RIGHT:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.8
      lookahead_dist: 0.8
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.5
      lookahead_time: 1.5
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: true
      rotate_to_heading_angular_vel: 0.0
      allow_reversing: false
      max_angular_accel: 1.0
      max_robot_pose_search_dist: 0.5

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

waypoint_follower:
  ros__parameters:
    use_sim_time: true

behavior_server:
  ros__parameters:
    use_sim_time: true

local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 5.0
    height: 5.0
    resolution: 0.05
    footprint: "[ [0.20, 0.12], [0.20, -0.12], [-0.20, -0.12], [-0.20, 0.12] ]"
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: scan
        max_obstacle_height: 1.0
        clearing: true
        marking: true
        data_type: "LaserScan"
        obstacle_range: 2.5
        raytrace_range: 3.0
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
      cost_scaling_factor: 3.0

global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 2.0
    publish_frequency: 1.0
    rolling_window: false
    resolution: 0.05
    footprint: "[ [0.20, 0.12], [0.20, -0.12], [-0.20, -0.12], [-0.20, 0.12] ]"
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: scan
        max_obstacle_height: 1.0
        clearing: true
        marking: true
        data_type: "LaserScan"
        obstacle_range: 2.5
        raytrace_range: 3.0
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
      cost_scaling_factor: 3.0

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - map_server
      - amcl
      - controller_server
      - planner_server
      - bt_navigator
      - waypoint_follower
      - behavior_server
